name: "Java CI with Maven"

on: push

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      - name: Setup JDK 21 for x86
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          # architecture: x64
      - name:  Build with Maven library 
        run: mvn -B package --file pom.xml